server:
  port: 8089

spring:
  application:
    name: ms-carrito
  
  # Configuración de Base de Datos H2
  datasource:
    url: jdbc:h2:mem:carritodb;DB_CLOSE_DELAY=-1;NOT_FIXED=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Habilitar consola web H2
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Configuración de JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true